server:
  port: 8761
  
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${vcap.application.uris[0]:localhost}:${server.port}/eureka/
spring:
  application:
    name: eureka-server
  zipkin:
    base-url: "http://${vcap.application.uris[0]:localhost}:9411/"
